// Schema of editable fields per page. Keys match the shape of the i18n
// translation objects in src/i18n/{en,fr}.ts so admin overrides can be merged in.

export interface PageFieldDef {
  key: string;
  label: string;
  multiline?: boolean;
  /** Default value shown as placeholder when the field has no direct flat i18n path (e.g. nested/synthetic fields). */
  defaultHint?: string;
}

export interface PageSchema {
  slug: string;
  label: string;
  translationKey: "founder" | "history" | "memoriam" | "home" | "team" | "donateP" | "membership" | "contact" | "footer";
  fields: PageFieldDef[];
}

export const PAGE_SCHEMAS: PageSchema[] = [
  {
    slug: "founder",
    label: "Fondateur",
    translationKey: "founder",
    fields: [
      { key: "aboutMufo", label: "Sur-titre" },
      { key: "title", label: "Titre" },
      { key: "subtitle", label: "Sous-titre", multiline: true },
      { key: "name", label: "Nom du fondateur" },
      { key: "role", label: "Rôle" },
      { key: "bio1", label: "Biographie §1", multiline: true },
      { key: "bio2", label: "Biographie §2", multiline: true },
      { key: "bio3", label: "Biographie §3", multiline: true },
      { key: "bio4", label: "Biographie §4", multiline: true },
      { key: "quote1", label: "Citation 1", multiline: true },
      { key: "quote2", label: "Citation 2", multiline: true },
    ],
  },
  {
    slug: "history",
    label: "Histoire",
    translationKey: "history",
    fields: [
      { key: "aboutMufo", label: "Sur-titre" },
      { key: "title", label: "Titre" },
      { key: "subtitle", label: "Sous-titre", multiline: true },
      { key: "meaningTitle", label: "Titre – Signification" },
      { key: "meaningP1", label: "Signification §1", multiline: true },
      { key: "meaningP2", label: "Signification §2", multiline: true },
      { key: "vision", label: "Titre Vision" },
      { key: "visionText", label: "Texte Vision", multiline: true },
      { key: "mission", label: "Titre Mission" },
      { key: "missionText", label: "Texte Mission", multiline: true },
      { key: "threePillars", label: "Titre – Piliers" },
      { key: "pillar1", label: "Pilier 1" },
      { key: "pillar1Desc", label: "Pilier 1 – description", multiline: true },
      { key: "pillar2", label: "Pilier 2" },
      { key: "pillar2Desc", label: "Pilier 2 – description", multiline: true },
      { key: "pillar3", label: "Pilier 3" },
      { key: "pillar3Desc", label: "Pilier 3 – description", multiline: true },
      { key: "coreValues", label: "Titre – Valeurs" },
      { key: "compassion", label: "Valeur : Compassion" },
      { key: "compassionDesc", label: "Compassion – description" },
      { key: "integrity", label: "Valeur : Intégrité" },
      { key: "integrityDesc", label: "Intégrité – description" },
      { key: "excellence", label: "Valeur : Excellence" },
      { key: "excellenceDesc", label: "Excellence – description" },
      { key: "equity", label: "Valeur : Équité" },
      { key: "equityDesc", label: "Équité – description" },
      { key: "legacy", label: "Valeur : Héritage" },
      { key: "legacyDesc", label: "Héritage – description" },
    ],
  },
  {
    slug: "memoriam",
    label: "In Memoriam",
    translationKey: "memoriam",
    fields: [
      { key: "aboutMufo", label: "Sur-titre" },
      { key: "title", label: "Titre" },
      { key: "subtitle", label: "Sous-titre", multiline: true },
      { key: "name", label: "Nom" },
      { key: "honor", label: "Mention d'honneur" },
      { key: "text1", label: "Texte §1", multiline: true },
      { key: "text2", label: "Texte §2", multiline: true },
      { key: "valuesTitle", label: "Titre – Valeurs" },
      { key: "responsibility", label: "Valeur : Responsabilité" },
      { key: "dignity", label: "Valeur : Dignité" },
      { key: "perseverance", label: "Valeur : Persévérance" },
      { key: "generationalImpact", label: "Valeur : Impact générationnel" },
      { key: "endQuote", label: "Citation finale", multiline: true },
    ],
  },
  {
    slug: "home",
    label: "Accueil",
    translationKey: "home",
    fields: [
      { key: "heroTitle", label: "Titre héro", multiline: true },
      { key: "heroSub", label: "Sous-titre héro", multiline: true },
      { key: "childrenSupported", label: "Libellé : Enfants soutenus" },
      { key: "fieldActions", label: "Libellé : Actions de terrain" },
      { key: "areasReached", label: "Libellé : Zones couvertes" },
      { key: "founded", label: "Libellé : Fondée en" },
      { key: "whoWeAre", label: "Titre – Qui sommes-nous" },
      { key: "whoWeAreText", label: "Texte – Qui sommes-nous", multiline: true },
      { key: "ourMission", label: "Titre – Notre mission" },
      { key: "missionText", label: "Texte – Mission", multiline: true },
      { key: "ourObjectives", label: "Titre – Nos objectifs" },
      { key: "obj1", label: "Objectif 1" },
      { key: "obj2", label: "Objectif 2" },
      { key: "obj3", label: "Objectif 3" },
      { key: "obj4", label: "Objectif 4" },
      { key: "threePillars", label: "Titre – Trois piliers" },
      { key: "pillarEdu", label: "Pilier : Éducation" },
      { key: "pillarEduDesc", label: "Éducation – description", multiline: true },
      { key: "pillarHealth", label: "Pilier : Santé" },
      { key: "pillarHealthDesc", label: "Santé – description", multiline: true },
      { key: "pillarDev", label: "Pilier : Développement" },
      { key: "pillarDevDesc", label: "Développement – description", multiline: true },
      { key: "ourStory", label: "Titre – Notre histoire" },
      { key: "millerLegacy", label: "Titre – L'héritage du meunier" },
      { key: "storyText", label: "Texte – Histoire", multiline: true },
      { key: "impactInAction", label: "Titre – Impact en action" },
      { key: "impactSub", label: "Sous-titre – Impact en action" },
      { key: "keyAchievements", label: "Titre – Réalisations clés" },
      { key: "achievement1", label: "Réalisation 1" },
      { key: "achievement2", label: "Réalisation 2" },
      { key: "achievement3", label: "Réalisation 3" },
      { key: "achievement4", label: "Réalisation 4" },
      { key: "ourPartners", label: "Titre – Nos partenaires" },
      { key: "partnersSub", label: "Sous-titre – Partenaires" },
      { key: "testimonialsTitle", label: "Titre – Témoignages" },
      { key: "quote", label: "Citation de clôture", multiline: true },
      { key: "mullersFoundation", label: "Signature citation" },
    ],
  },
  {
    slug: "team",
    label: "Équipe",
    translationKey: "team",
    fields: [
      { key: "title", label: "Titre" },
      { key: "subtitle", label: "Sous-titre", multiline: true },
      { key: "governanceTitle", label: "Titre – Gouvernance" },
      { key: "governanceText", label: "Texte – Gouvernance", multiline: true },
    ],
  },
  {
    slug: "donate",
    label: "Faire un don",
    translationKey: "donateP",
    fields: [
      { key: "heroTitle", label: "Titre héro", multiline: true },
      { key: "heroSub", label: "Sous-titre héro", multiline: true },
      { key: "howToDonate", label: "Titre – Comment donner" },
      { key: "bankTransfer", label: "Méthode : Virement bancaire" },
      { key: "bankDesc", label: "Virement – description" },
      { key: "mobileMoney", label: "Méthode : Mobile Money" },
      { key: "mobileDesc", label: "Mobile Money – description" },
      { key: "paypal", label: "Méthode : PayPal" },
      { key: "paypalDesc", label: "PayPal – description" },
      { key: "zelle", label: "Méthode : Zelle" },
      { key: "zelleDesc", label: "Zelle – description" },
      { key: "fundsAllocation", label: "Titre – Répartition des fonds" },
      { key: "education", label: "Catégorie : Éducation" },
      { key: "eduPct", label: "Éducation – pourcentage", defaultHint: "60" },
      { key: "health", label: "Catégorie : Santé" },
      { key: "healthPct", label: "Santé – pourcentage", defaultHint: "25" },
      { key: "philanthropy", label: "Catégorie : Philanthropie" },
      { key: "philPct", label: "Philanthropie – pourcentage", defaultHint: "10" },
      { key: "administration", label: "Catégorie : Administration" },
      { key: "adminPct", label: "Administration – pourcentage", defaultHint: "5" },
    ],
  },
  {
    slug: "membership",
    label: "Adhésion",
    translationKey: "membership",
    fields: [
      { key: "title", label: "Titre" },
      { key: "subtitle", label: "Sous-titre", multiline: true },
      { key: "standard", label: "Palier : Standard" },
      { key: "standardDesc", label: "Standard – description", multiline: true },
      { key: "supporter", label: "Palier : Supporter" },
      { key: "supporterDesc", label: "Supporter – description", multiline: true },
      { key: "ambassador", label: "Palier : Ambassadeur" },
      { key: "ambassadorDesc", label: "Ambassadeur – description", multiline: true },
      { key: "mostPopular", label: "Badge – Le plus populaire" },
      { key: "joinNow", label: "Bouton – Rejoindre" },
      { key: "benefit_quarterly", label: "Avantage : Newsletter trimestrielle", defaultHint: "Quarterly newsletter" },
      { key: "benefit_annual", label: "Avantage : Rapport annuel", defaultHint: "Annual impact report" },
      { key: "benefit_invitation", label: "Avantage : Invitation événements", defaultHint: "Invitation to events" },
      { key: "benefit_certificate", label: "Avantage : Certificat", defaultHint: "Certificate of membership" },
      { key: "benefit_priority", label: "Avantage : Accès prioritaire", defaultHint: "Priority event access" },
      { key: "benefit_recognition", label: "Avantage : Reconnaissance site", defaultHint: "Recognition on website" },
      { key: "benefit_directUpdates", label: "Avantage : Mises à jour directes", defaultHint: "Direct project updates" },
      { key: "benefit_exclusiveWebinars", label: "Avantage : Webinaires exclusifs", defaultHint: "Exclusive webinars" },
      { key: "benefit_advisory", label: "Avantage : Comité consultatif", defaultHint: "Advisory board invitation" },
      { key: "benefit_fieldVisit", label: "Avantage : Visite terrain", defaultHint: "Field visit opportunities" },
      { key: "benefit_dashboard", label: "Avantage : Tableau de bord perso.", defaultHint: "Personal impact dashboard" },
      { key: "benefit_vip", label: "Avantage : Événements VIP", defaultHint: "VIP recognition events" },
      { key: "benefit_coBranding", label: "Avantage : Co-branding", defaultHint: "Co-branding opportunities" },
    ],
  },
  {
    slug: "contact",
    label: "Contact",
    translationKey: "contact",
    fields: [
      { key: "title", label: "Titre" },
      { key: "subtitle", label: "Sous-titre", multiline: true },
      { key: "sendMessage", label: "Titre – Formulaire" },
      { key: "ourOffices", label: "Titre – Nos bureaux" },
      { key: "headquarters", label: "Libellé : Siège" },
      { key: "representation", label: "Libellé : Représentation" },
      { key: "drCongo", label: "Pays 1" },
      { key: "kinshasa", label: "Ville 1" },
      { key: "usa", label: "Pays 2" },
      { key: "usaOffice", label: "Ville 2" },
      { key: "france", label: "Pays 3" },
      { key: "franceOffice", label: "Ville 3" },
      { key: "canada", label: "Pays 4" },
      { key: "canadaOffice", label: "Ville 4" },
      { key: "mapPlaceholder", label: "Texte – Emplacement carte" },
    ],
  },
  {
    slug: "footer",
    label: "Pied de page",
    translationKey: "footer",
    fields: [
      { key: "desc", label: "Description", multiline: true },
    ],
  },
];

export const getPageSchema = (slug: string) =>
  PAGE_SCHEMAS.find((p) => p.slug === slug);
